### ISSUE TITLE
Sugestões #1postperday

### ISSUE THREAD

**Issue by fdaciuk** [fdaciuk/fdaciuk.github.io#1]
Sobre o que você gostaria de ler no #1postperday?

Preferencialmente assuntos relacionados a **Javascript**, **HTML**, **CSS**, **WordPress** e ferramentas para usar com esses caras :)
Se eu conhecer o assunto, irei escrever sobre ele com certeza!
Se não conhecer, irei pesquisar sobre para poder escrever :)

Deixe sua sugestão!

> Quer participar do #1postperday? [Veja como aqui](http://blog.da2k.com.br/2014/12/31/um-post-por-dia/)

**Comment by luisfernandomangia** [comment]
html5

**Comment by fdaciuk** [comment]
O que você acha que seria legal falar de html5 @luisfernandomangia? 
Semântica das tags? alguma nova API específica? Outro assunto?

Valeu pela sugestão :D

**Comment by luisfernandomangia** [comment]
acho fundamental focar em api's como geolocalização e outras. Creio eu que o html5 básico muita gente já entenda @fdaciuk .

**Comment by fdaciuk** [comment]
Massa! Sugestão anotada :dancer: :dancer:

**Comment by mandado** [comment]
Opa!! fala @fdaciuk, beleza cara ? então minha sugestão um guia para criar temas para wordpress se possível ou um norte.

**Comment by willianis4w** [comment]
A loucura que é a vida de quem quer se manter atualizado o tempo todo. ;)

**Comment by fdaciuk** [comment]
Sugestão anotada @mandado :D 
Tem que ser né @willianis4w haha :P

**Comment by nandomoreirame** [comment]
Que tal um pouco de AngularJS... :)
Como usa-lo em projetos pequenos (não sistemas e apps), usando sua forma correta de desenvolvimento... estou sujerindo isso porque ainda é obscura a ideia e sempre penso no Angular como um projeto grande...

**Comment by fdaciuk** [comment]
É uma boa @nandomoreiraweb! Dica anotada ;)

**Comment by studiooffice** [comment]
Fala @fdaciuk, uma dica Multiline String e Multidimensional Array em PHP? Abraços!

**Comment by eltondev** [comment]
Fala @fdaciuk uma dia Multiline String e Multidimensional Array em PHP.

**Comment by fdaciuk** [comment]
Boa! Anotado @eltondev :D

**Comment by ghost** [comment]
live-reload integrado com sass no gulp =)

**Comment by fdaciuk** [comment]
Ótimo tema @padilhalucas! Anotado :dancer:

**Comment by witerbino** [comment]
Web Speech API seria legal falar sobre essa API =)

**Comment by fdaciuk** [comment]
Boa @witerbino! Web Speech é da hora xD
Anotado! :D

**Comment by fhferreira** [comment]
AngularJS vs EmberJs

**Comment by fdaciuk** [comment]
Legal @fhferreira! É legal fazer uma comparação.. mas não tenho conhecimento de Ember ainda, então esse pode demorar um pouco pra sair até eu aprender pra poder comparar xD
Valeu pela sugestão! :smile:

**Comment by marcosfreitas** [comment]
@fdaciuk por favor, escreva sobre Mutation Observers.

**Comment by marcosfreitas** [comment]
@fdaciuk em PHP que tal explicar um pouco sobre Traits e NameSpaces? Quando e como usar cada uma delas.

**Comment by fdaciuk** [comment]
Ótimas sugestões @marcosfreitas! Obrigado :D

**Comment by marcelgsantos** [comment]
@fdaciuk, parabéns pelo empenho!

Os artigos s/ GitHub estão ficando sensacionais e muito bem explicados/escritos. ;) Isso facilita o entendimento para quem não está acostumado a utilizar a ferramenta e enriquece o aprendizado.

Minhas sugestões são: continuar com artigos s/ GitHub (ou até criar uma série s/ GitHub e ferramentas relacionadas c/ TravisCI, Trello entre outras), ReactJS e BackboneJS (e utilizando ambos em conjunto).

Valeu! ;)

**Comment by fdaciuk** [comment]
Ótimo assunto @marcelgsantos! Fico feliz em estar ajudando  :)
Sugestões anotadas :D

**Comment by matheusilario** [comment]
@fdaciuk seus posts tem ajudado bastante, o problema &eacute; utilizar tudo rs mas agente da um jeito.
Gostaria de sugerir como tema a cria&ccedil;&atilde;o de plugins Wp com tabelas personalizadas no banco de dados, wp_list_table e formul&aacute;rios.

Estou desenvolvendo um e garrei em alguns pontos, sei como fazer em php mas na hora de fazer com WP fico procurando na documenta&ccedil;&atilde;o e gostaria de ver se to fazendo da forma certa. Vlw

**Comment by stewones** [comment]
Parabéns ae pela iniciativa de escrever mais conteúdo em pt_BR
Minha sugestão para quando for falar de angular.js X ember.js

http://www.techwars.io/fight/angularjs/emberjs/

**Comment by fdaciuk** [comment]
Massa @matheusilario! O ideal é somente criar tabelas específicas se realmente for necessário, e fizer sentido. Normalmente você consegue trabalhar sempre dentro da estrutura do próprio WP :)

Mas é um bom assunto! Anotado :)

**Comment by fdaciuk** [comment]
Valeu @stewones!
Obrigado pelo link :dancer:

**Comment by fabricionaweb** [comment]
Fala sobre yield e function\* (iterators e generators)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield

**Comment by jeffesonmaia** [comment]
Ja que tem bastante assunto de Wordpress não seria bom falar de RequireJS + Wordpress ?

**Comment by fdaciuk** [comment]
Boa @fabricionaweb :dancer: 
Anotado :smile:

**Comment by fdaciuk** [comment]
Boa dica @jeffesonmaia! Anotado também :smile:

**Comment by jamesclebio** [comment]
Fala, @fdaciuk! Acho que seria interessante você escrever sobre suas preferências de coding style, tipo [essa parada](https://github.com/zenorocha/my-coding-style) que o Zeno fez... ;D

**Comment by fdaciuk** [comment]
Boa @jamesclebio :sparkles: 
Comecei a escrever meu style guide uma vez, mas não dei continuidade. Farei isso! Obrigado pela sugestão :smile:

**Comment by alannsiqueira** [comment]
Api REST e autenticação via tokens [symfony2 ou mean]

**Comment by fdaciuk** [comment]
Legal @alannsiqueira! Obrigado pela sugestão :smile:

**Comment by fdaciuk** [comment]
Todas as dicas estão anotadas! Obrigado pela colaboração de todos \o/ 
Em 2015 não deu pra escrever tudo, mas vamos continuar! :D 

Para novas sugestões, podem usar esse repositório: https://github.com/LFeh/poste-mais
:dancer: :shipit:
